server:
 port: 8080
spring:
 jpa:
  database: mysql
  show-sql: true
  hibernate:
   ddl-auto: create
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test
  username: root
  password: root
  name: test